### ISSUE TITLE
replace email in .travis.yml

### ISSUE THREAD

**Issue by jamesturk** [OpenPrecincts/openprecincts-web#106]
Hi @indraneel ! 

Hope all's well up there.  I was wondering if you'd mind switching the email  in .travis.yml to yours, or at least removing mine?  Still getting notifications when builds pass/fail :)

**Comment by indraneel** [comment]
Sorry about that! Closed https://github.com/OpenPrecincts/openprecincts-web/commit/442b925d804855f699e27cb60408b0b2a00e1f56
