### ISSUE TITLE
Make Site Mobile Friendly

### ISSUE THREAD

**Issue by Ccheng26** [OpenPrecincts/openprecincts-web#53]
Links to State Overview, About, Report An Issue do not appear mobile device (attempted to view on iOS 6 version 12.2.

**Comment by jamesturk** [comment]
Hi Connie,

Thanks- making the site a bit more mobile friendly for browsing is
definitely something I'd like to do, however the core functionality will
require a desktop browser as the planned GIS functionality/etc. just isn't
well suited to a mobile app.
